/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Modelo.dto.Producto;
import Modelo.dto.Categorias;
import Metodos.GestorProductosYCategorias2;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Eduardo
 */

public class VentanaProductos2 extends javax.swing.JFrame {
     private GestorProductosYCategorias2 gestor;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaProductos2.class.getName());

    /**
     * Creates new form VentanaProductos
     */
    public VentanaProductos2(ArrayList<Producto> listaProducto, ArrayList<Categorias> listacategoria) {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        gestor = new GestorProductosYCategorias2(listaProducto, listacategoria, modelo);
        gestor.actualizarTabla();
    }
                                                                                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtStockPro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProveedorPro = new javax.swing.JTextField();
        txtdescPro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStockminPro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVentaPro = new javax.swing.JTextField();
        txtpCompraPro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcodPro = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        txtnomPro = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtCateProd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelLazo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtFV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 73, 129, -1));

        txtStockPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtStockPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 204, 111, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setText("Descripcion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 102, 129, -1));

        txtProveedorPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtProveedorPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 267, 111, -1));

        txtdescPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtdescPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 99, 111, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel11.setText("Stock minimo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 236, 129, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("P. Compra:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 137, 129, -1));

        txtStockminPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtStockminPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 233, 111, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setText("P. Venta:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 172, 129, -1));

        txtVentaPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtVentaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 169, 111, -1));

        txtpCompraPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtpCompraPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 134, 111, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setText("Stock:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 207, 129, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setText("Proveedor:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 270, 129, -1));

        txtcodPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtcodPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 42, 111, -1));

        btnguardar.setBackground(new java.awt.Color(204, 204, 204));
        btnguardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 99, -1));

        txtnomPro.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtnomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 70, 111, -1));

        btnModificar.setBackground(new java.awt.Color(204, 204, 204));
        btnModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 90, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 45, 96, -1));

        tablaProductos.setBackground(new java.awt.Color(204, 204, 204));
        tablaProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "PrecioCompra", "PrecioVenta", "Stock", "Stock minimo", "Proveedor", "Categoria", "FV"
            }
        ));
        jScrollPane2.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 769, 304));

        jLabel12.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel12.setText("Categoria");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 305, 129, -1));

        txtCateProd.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(txtCateProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 302, 111, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tiendaLazo.png"))); // NOI18N
        jPanel1.add(jLabelLazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 484, 250));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel10.setText("Fecha de Vencimiento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 171, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 80, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 80, -1));

        txtFV.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanel1.add(txtFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 281, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        String codigo  = txtcodPro.getText();
        String nombre = txtnomPro.getText();
        String descripcion = txtdescPro.getText();
        double precioCompra = Double.parseDouble(txtpCompraPro.getText());
        double precioVenta = Double.parseDouble(txtVentaPro.getText());
        int stock = Integer.parseInt(txtStockPro.getText());
        String proveedor = txtProveedorPro.getText();
        String idCategoria = "CAT-01";
        String textoFecha = txtFV.getText(); // El campo que tiene "2025-12-31"
        // Y valida antes de convertir (porque si está vacío también dará error)
        LocalDate fechaVencimiento = null;
        if (textoFecha != null && !textoFecha.isEmpty()) {
    fechaVencimiento = LocalDate.parse(textoFecha);
}
        //LocalDate fechaVencimiento = LocalDate.parse(txtFV.getText());
        int stockMinimo = Integer.parseInt(txtStockminPro.getText());
        boolean exito = gestor.agregarProducto(codigo, nombre, descripcion,
            precioCompra, precioVenta, stock, stockMinimo,
            idCategoria, proveedor, fechaVencimiento);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Producto guardado correctamente");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Verifica los datos");
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if (fila >= 0) {
            try {
                String codigo = txtcodPro.getText();
                String nombre = txtnomPro.getText();
                String descripcion = txtdescPro.getText();
                double precioCompra = Double.parseDouble(txtpCompraPro.getText());
                double precioVenta = Double.parseDouble(txtVentaPro.getText());
                int stock = Integer.parseInt(txtStockPro.getText());
                int stockMinimo = 5;
                String proveedor = txtProveedorPro.getText();
                String idCategoria = "CAT-01";
                LocalDate fechaVencimiento = LocalDate.parse(txtFV.getText());

                boolean modificado = gestor.editarProducto(fila, codigo, nombre, descripcion,
                    precioCompra, precioVenta, stock, stockMinimo,
                    idCategoria, proveedor, fechaVencimiento);
                if (modificado) {
                    JOptionPane.showMessageDialog(this, "Producto modificado");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al modificar");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if (fila >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar producto?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                boolean eliminado = gestor.eliminarProducto(fila);
                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Producto eliminado");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
public void limpiarCampos() { //Evita repetir el mismo código en cada botón.
    txtcodPro.setText(""); //Se llama después de guardar, modificar o eliminar para dejar el formulario limpio.
    txtnomPro.setText(""); //Mejora la legibilidad y mantenimiento del código.
    txtdescPro.setText("");
    txtpCompraPro.setText("");
    txtVentaPro.setText("");
    txtStockPro.setText("");
    txtStockminPro.setText("");
    txtProveedorPro.setText("");
    txtFV.setText("");
}
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLazo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCateProd;
    private javax.swing.JTextField txtFV;
    private javax.swing.JTextField txtProveedorPro;
    private javax.swing.JTextField txtStockPro;
    private javax.swing.JTextField txtStockminPro;
    private javax.swing.JTextField txtVentaPro;
    private javax.swing.JTextField txtcodPro;
    private javax.swing.JTextField txtdescPro;
    private javax.swing.JTextField txtnomPro;
    private javax.swing.JTextField txtpCompraPro;
    // End of variables declaration//GEN-END:variables
}

