/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Modelo.dto.HistoriaVenta;
import Modelo.dto.Producto;
import java.util.ArrayList; 

/**
 *
 * @author diazq
 */
public class VentanaReportes extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReportes.class.getName());
    
    // 1. Declarar variables internas (para guardar las listas recibidas)
    private ArrayList<Producto> listaGeneralP; 
    private ArrayList<HistoriaVenta> listaGeneralV; // O listaHistorial, usa el nombre que tengas en Principal.java

    // 2. Constructor MODIFICADO
    public VentanaReportes(ArrayList<Producto> listaProductos, ArrayList<HistoriaVenta> listaVentas) {
        initComponents();
        this.listaGeneralV = listaVentas;
        this.listaGeneralP = listaProductos;
        }
    

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExportarInventario = new javax.swing.JButton();
        btnExportarAgotados = new javax.swing.JButton();
        btnExportarVentas = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExportarInventario.setText("Inventario actualizado");
        btnExportarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarInventarioActionPerformed(evt);
            }
        });

        btnExportarAgotados.setText("Productos con bajo stock");
        btnExportarAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarAgotadosActionPerformed(evt);
            }
        });

        btnExportarVentas.setText("Ventas realizadas");
        btnExportarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarVentasActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver)
                    .addComponent(btnExportarInventario)
                    .addComponent(btnExportarVentas)
                    .addComponent(btnExportarAgotados))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnVolver)
                .addGap(76, 76, 76)
                .addComponent(btnExportarInventario)
                .addGap(38, 38, 38)
                .addComponent(btnExportarAgotados)
                .addGap(41, 41, 41)
                .addComponent(btnExportarVentas)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarInventarioActionPerformed
        Inventario vInventario = new Inventario(this.listaGeneralP);
        vInventario.setVisible(true);
        vInventario.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnExportarInventarioActionPerformed

    private void btnExportarAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarAgotadosActionPerformed
        BajoStock bajoStock = new BajoStock(this.listaGeneralP);
        bajoStock.setVisible(true);
        bajoStock.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnExportarAgotadosActionPerformed

    private void btnExportarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarVentasActionPerformed
        Ventas hVentas = new Ventas(this.listaGeneralV);
        hVentas.setVisible(true);
        hVentas.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnExportarVentasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarAgotados;
    private javax.swing.JButton btnExportarInventario;
    private javax.swing.JButton btnExportarVentas;
    private javax.swing.JButton btnVolver;
    // End of variables declaration//GEN-END:variables
}
